[book]
authors = ["SAF Contributors"]
language = "en"
src = "src"
title = "SAF Documentation"

[build]
build-dir = "build"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/ThePatrickStar/static-analyzer-factory"
additional-css = ["src/theme.css", "src/custom.css", "src/global-nav.css"]
additional-js = ["src/global-nav.js"]
