//! Constraint types for points-to analysis.
//!
//! The analysis extracts constraints from AIR instructions and solves them
//! to compute points-to sets. Each constraint type models a different
//! pointer operation.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use saf_core::ids::{LocId, ValueId};

use super::location::FieldPath;

// =============================================================================
// Constraint types
// =============================================================================

/// Address-of constraint: `ptr` points to `loc`.
///
/// Generated by: `Alloca`, `Global`, `HeapAlloc`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct AddrConstraint {
    /// The pointer value that receives the address.
    pub ptr: ValueId,
    /// The location being addressed.
    pub loc: LocId,
}

/// Copy constraint: `dst`'s points-to set includes `src`'s.
///
/// Generated by: Copy, Cast, Phi, Select, function params/returns.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct CopyConstraint {
    /// The destination pointer value.
    pub dst: ValueId,
    /// The source pointer value.
    pub src: ValueId,
}

/// Load constraint: `dst` gets pointed-to values of locations in `src_ptr`.
///
/// Generated by: Load.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct LoadConstraint {
    /// The destination value receiving the loaded pointer.
    pub dst: ValueId,
    /// The pointer being dereferenced.
    pub src_ptr: ValueId,
}

/// Store constraint: locations in `dst_ptr` get values from `src`.
///
/// Generated by: Store.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct StoreConstraint {
    /// The pointer being stored through.
    pub dst_ptr: ValueId,
    /// The value being stored.
    pub src: ValueId,
}

/// GEP (get element pointer) constraint: `dst` points to field offset of `src_ptr`.
///
/// Generated by: Gep.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct GepConstraint {
    /// The destination pointer.
    pub dst: ValueId,
    /// The source base pointer.
    pub src_ptr: ValueId,
    /// The field path to apply.
    pub path: FieldPath,
    /// Index operands for each `PathStep::Index` in the path.
    ///
    /// Each `Some(ValueId)` corresponds to an `Index` step in the path
    /// (in order). The solver uses these to resolve `IndexExpr::Constant`
    /// (if the ValueId is a known constant) or `IndexExpr::Symbolic`
    /// (if the ValueId is a runtime value).
    ///
    /// This is empty when index sensitivity is disabled or for paths
    /// that contain only `Field` steps.
    pub index_operands: Vec<ValueId>,
}

// =============================================================================
// Constraint set
// =============================================================================

/// Collection of all constraints extracted from a program.
///
/// Uses `BTreeSet` for deterministic iteration order (NFR-DET).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ConstraintSet {
    /// Address-of constraints.
    pub addr: BTreeSet<AddrConstraint>,
    /// Copy constraints.
    pub copy: BTreeSet<CopyConstraint>,
    /// Load constraints.
    pub load: BTreeSet<LoadConstraint>,
    /// Store constraints.
    pub store: BTreeSet<StoreConstraint>,
    /// GEP constraints.
    pub gep: BTreeSet<GepConstraint>,
}

impl ConstraintSet {
    /// Get the total number of constraints.
    #[must_use]
    pub fn total_count(&self) -> usize {
        self.addr.len() + self.copy.len() + self.load.len() + self.store.len() + self.gep.len()
    }

    /// Check if the constraint set is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.total_count() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use saf_core::ids::{LocId, ValueId};

    #[test]
    fn addr_constraint_equality() {
        let c1 = AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        };
        let c2 = AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        };
        let c3 = AddrConstraint {
            ptr: ValueId::new(2),
            loc: LocId::new(100),
        };

        assert_eq!(c1, c2);
        assert_ne!(c1, c3);
    }

    #[test]
    fn copy_constraint_equality() {
        let c1 = CopyConstraint {
            dst: ValueId::new(1),
            src: ValueId::new(2),
        };
        let c2 = CopyConstraint {
            dst: ValueId::new(1),
            src: ValueId::new(2),
        };

        assert_eq!(c1, c2);
    }

    #[test]
    fn load_constraint_equality() {
        let c = LoadConstraint {
            dst: ValueId::new(1),
            src_ptr: ValueId::new(2),
        };
        assert_eq!(c.dst, ValueId::new(1));
        assert_eq!(c.src_ptr, ValueId::new(2));
    }

    #[test]
    fn store_constraint_equality() {
        let c = StoreConstraint {
            dst_ptr: ValueId::new(1),
            src: ValueId::new(2),
        };
        assert_eq!(c.dst_ptr, ValueId::new(1));
        assert_eq!(c.src, ValueId::new(2));
    }

    #[test]
    fn gep_constraint_with_path() {
        let path = super::super::location::FieldPath::field(0);
        let c = GepConstraint {
            dst: ValueId::new(1),
            src_ptr: ValueId::new(2),
            path: path.clone(),
            index_operands: vec![],
        };
        assert_eq!(c.path, path);
        assert!(c.index_operands.is_empty());
    }

    #[test]
    fn gep_constraint_with_index_operands() {
        let path = super::super::location::FieldPath::index();
        let idx_val = ValueId::new(100);
        let c = GepConstraint {
            dst: ValueId::new(1),
            src_ptr: ValueId::new(2),
            path: path.clone(),
            index_operands: vec![idx_val],
        };
        assert_eq!(c.path, path);
        assert_eq!(c.index_operands.len(), 1);
        assert_eq!(c.index_operands[0], idx_val);
    }

    #[test]
    fn constraint_set_default_is_empty() {
        let cs = ConstraintSet::default();
        assert!(cs.addr.is_empty());
        assert!(cs.copy.is_empty());
        assert!(cs.load.is_empty());
        assert!(cs.store.is_empty());
        assert!(cs.gep.is_empty());
    }

    #[test]
    fn constraint_set_add_addr() {
        let mut cs = ConstraintSet::default();
        let c = AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        };
        cs.addr.insert(c.clone());
        assert_eq!(cs.addr.len(), 1);
        assert!(cs.addr.contains(&c));
    }

    #[test]
    fn constraint_set_deduplicates() {
        let mut cs = ConstraintSet::default();
        let c = AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        };
        cs.addr.insert(c.clone());
        cs.addr.insert(c.clone());
        assert_eq!(cs.addr.len(), 1);
    }

    #[test]
    fn constraint_set_deterministic_iteration() {
        let mut cs = ConstraintSet::default();

        // Insert in "random" order
        cs.addr.insert(AddrConstraint {
            ptr: ValueId::new(3),
            loc: LocId::new(300),
        });
        cs.addr.insert(AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        });
        cs.addr.insert(AddrConstraint {
            ptr: ValueId::new(2),
            loc: LocId::new(200),
        });

        // Should iterate in sorted order
        let ptrs: Vec<_> = cs.addr.iter().map(|c| c.ptr.raw()).collect();
        assert_eq!(ptrs, vec![1, 2, 3]);
    }

    #[test]
    fn constraint_ordering() {
        let c1 = AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        };
        let c2 = AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(200),
        };
        let c3 = AddrConstraint {
            ptr: ValueId::new(2),
            loc: LocId::new(100),
        };

        assert!(c1 < c2); // Same ptr, different loc
        assert!(c1 < c3); // Different ptr
    }

    #[test]
    fn constraint_set_total_count() {
        let mut cs = ConstraintSet::default();
        cs.addr.insert(AddrConstraint {
            ptr: ValueId::new(1),
            loc: LocId::new(100),
        });
        cs.copy.insert(CopyConstraint {
            dst: ValueId::new(2),
            src: ValueId::new(1),
        });
        cs.load.insert(LoadConstraint {
            dst: ValueId::new(3),
            src_ptr: ValueId::new(1),
        });

        assert_eq!(cs.total_count(), 3);
    }
}
