#!/usr/bin/env bash
# Reproduce an SV-COMP-style BenchExec run for SAF at competition resource limits
# (plan 203). Wraps `saf verify` exactly as the competition would, via the vendored
# tool-info module benchexec/tools/saf.py.
#
#   scripts/run_benchexec_svcomp.sh <benchmark-def.xml> [rundefinition-name]
#
# Examples (run on the VM, inside the dev container — LLVM + benchexec present):
#   # Full official-style run, all properties:
#   scripts/run_benchexec_svcomp.sh benchmark-defs/saf.xml
#   # Only the unreach-call rundefinition:
#   scripts/run_benchexec_svcomp.sh benchmark-defs/saf.xml SV-COMP_unreach-call
#   # Just the non-overfitting HOLDOUT slice (generated by svcomp_split.py):
#   scripts/run_benchexec_svcomp.sh tests/benchmarks/svcomp-splits/holdout.bench.xml
#
# This produces raw verdicts + collected witnesses + a table-generator score table.
# It does NOT run the witness validators (that is a separate, heavier stage). For a
# CONFIRMED-witness score without the full validation pipeline, use the lighter
# scripts/svcomp_split_eval.py --confirm-witness on the same split.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BENCHDEF="${1:?usage: run_benchexec_svcomp.sh <benchmark-def.xml> [rundefinition-name]}"
RUNDEF="${2:-}"
OUTDIR="${SAF_BENCHEXEC_OUT:-$REPO_ROOT/results/benchexec}"
THREADS="${SAF_BENCHEXEC_THREADS:-1}"     # parallel runs; 1 = most faithful timing
SAF_BIN_DIR="${SAF_BIN_DIR:-$REPO_ROOT/target/release}"

command -v benchexec >/dev/null 2>&1 || {
    echo "ERROR: benchexec not installed. In the dev image: pip install benchexec" >&2
    exit 1; }
[ -x "$SAF_BIN_DIR/saf" ] || {
    echo "ERROR: saf binary not found at $SAF_BIN_DIR/saf" >&2
    echo "  build it: cargo build --release -p saf-cli" >&2
    exit 1; }

# BenchExec resolves tool="saf" to the module benchexec.tools.saf. Install the
# vendored tool-info module into the active benchexec package so it is importable.
TOOLS_DIR="$(python3 -c 'import benchexec.tools, os; print(os.path.dirname(benchexec.tools.__file__))')"
cp "$REPO_ROOT/benchexec/tools/saf.py" "$TOOLS_DIR/saf.py"
echo "[run] installed tool-info -> $TOOLS_DIR/saf.py"

# tool_locator.find_executable("saf") searches PATH.
export PATH="$SAF_BIN_DIR:$PATH"

mkdir -p "$OUTDIR"
args=(--output "$OUTDIR" --numOfThreads "$THREADS")
[ -n "$RUNDEF" ] && args+=(--rundefinition "$RUNDEF")
# Extra flags (e.g. --no-container on hosts without cgroup delegation) via env.
if [ -n "${SAF_BENCHEXEC_EXTRA:-}" ]; then
    # shellcheck disable=SC2206
    args+=(${SAF_BENCHEXEC_EXTRA})
fi

echo "[run] benchexec ${args[*]} $BENCHDEF"
benchexec "${args[@]}" "$BENCHDEF"

echo "[run] aggregating score table with table-generator"
shopt -s nullglob
results=("$OUTDIR"/*.xml.bz2)
if [ ${#results[@]} -gt 0 ]; then
    table-generator -o "$OUTDIR" "${results[@]}"
    echo "[run] score table(s) written under $OUTDIR"
else
    echo "[run] WARNING: no results XML found in $OUTDIR"
fi
